version: '2'

services:
  db:
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
    volumes:
       - /root/postgres_dbdata:/var/lib/postgresql/data
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  app:
    environment:
      DATABASE_URL: postgres://django_user:django_pass@db/django_db
      DJANGO_MANAGEPY_MIGRATE: "on"
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "8000:8000"
