version: '2'

services:
  db:
    environment:
      POSTGRES_DB: djangodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    image: postgres:9.2.23
    expose:
      - "5432"
  app:
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/djangodb
      DJANGO_MANAGEPY_MIGRATE: "on"
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "8000:8000"
